Add hardhat tests
morpho-dao/curve-factory pull request #2
Opened 2023-03-27 09:19 UTC by Rubilmax

2023-03-28 20:26 UTC, MerlinEgalite commented
so hardhat has been abandoned?

2023-03-29 06:45 UTC, Rubilmax commented
> so hardhat has been abandoned?

Indeed, for speed, fuzzing capacity & smart-contract integration tests (return value testing)

2023-04-05 09:23 UTC, MerlinEgalite requested changes

2023-04-05 09:23 UTC, MerlinEgalite commented on src/DepositZapMorphoAaveV2USD.vy
> +    def coins(i: int128) -> address: view
?

2023-04-05 09:36 UTC, MerlinEgalite approved these changes

2023-04-05 12:58 UTC, pakim249CAL approved these changes

2023-04-14 14:53 UTC, merged